add solution for 04-lection2 histogram and skeleton
js-tasks-ru/htmlcss-20211125_voffkarus pull request #5
Opened 2021-12-14 21:53 UTC by OursonSucre

2021-12-14 21:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-14 23:00 UTC, GSemikozov requested changes

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
ширину и высоту не будем фиксировать)

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    grid-template-rows: 40px 43px 1fr;
все-таки такая разметка на гридах избыточна) ряды и колонки совсем не информативны)
на самом деле здесь 2 ряда, и 0 колонок, поскольку формально на колонки мы можем разбить только верхнюю часть)

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-left: 3px;
лучше либо gap на уровне родителя, либо margin-right 1px

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +:root {
root определяется глобально на уровне main.css, соответственно там и надо добавлять глобальные переменные. Если же это локальная переменная - тогда. прямо в классе блока

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
ширину и высоту не будем фиксировать

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_wrapper {
это скорее не враппер (то во что заворачиваем), а inner (то, ЧТО заворачиваем). Но более подходящий класс будет например .skeleton__row (__box)

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_wrapper:last-child {
и еще тут путаница с синтаксисом класса - это элемент, а не модификатор, поэтому записывать надо так -  .skeleton__wrapper

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_wrapper__avatar {
.skeleton_wrapper__avatar -> .skeleton__avatar

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-left: 24px;
вместо того чтобы каждому дочернему элементу задавать марджины, лучше один раз определить нужные внутренние (паддинги) отступы родителя

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_wrapper__name {
.skeleton_wrapper__name -> .skeleton__name (но гораздо правильнее объединить __name, __title и __desc в один элемент __line, ширину которого будем менять через модификаторы)

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-left: 16px;
про марджины уже писал, актуально тут и ниже

2021-12-14 23:00 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
тут и ниже - ширину лучше задавать в процентах, чтобы позаботиться об адаптивности

2021-12-15 09:42 UTC, OursonSucre commented on 04-lection2/01-histogram/histogram.css
> +    margin-left: 3px;
Сделал gap

2021-12-15 09:43 UTC, OursonSucre commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
Убрал свойства, компонент стал резиновым, это нормально?

2021-12-15 10:02 UTC, OursonSucre commented on 04-lection2/01-histogram/histogram.css
> +    grid-template-rows: 40px 43px 1fr;
Да ты прав, переделал на Flex и стало гораздо минималистичнее :)

2021-12-15 10:04 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +:root {
Поправил.

2021-12-15 10:05 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
Поправил.

2021-12-15 10:09 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_wrapper:last-child {
Поправил.

2021-12-15 10:09 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_wrapper__avatar {
Поправил.

2021-12-15 10:17 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_wrapper__name {
Отличная идея, как то я до этого модификаторами пренебрегал :)

2021-12-15 10:22 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-left: 24px;
Получилось.

2021-12-15 10:23 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-left: 16px;
Поправил.

2021-12-15 10:27 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton_wrapper {
Не совсем тут понял. Наверное можно было бы попробовать обойтись вообще без оборачивания, используя flex [grow, shrink, basis], но видимо где-то я что то не учитываю.

2021-12-15 10:29 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
Вот тут не получилось, если не задавать ширину явно, они просто занимают ноль в ширину. Я вроде и понимаю что проценты - это от ширины родителя, но что то так и не понял как именно тут его сделать отзывчивым (содержимое то пустое!)

2021-12-15 10:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-16 09:13 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
абсолютно)

2021-12-16 09:15 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
а мы же через модификаторы и задаем ширину в процентах, что позволит растянуть элемент на столько, на сколько надо

2021-12-16 09:19 UTC, GSemikozov requested changes

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-wrap: wrap;
задаем паддинги здесь

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-left: 24px;
чтобы не задавать паддинги здесь

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-right: 29px;
здесь

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-left: 24px;
здесь

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 26px;
здесь

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram_barswrapper__bar {
.histogram_barswrapper__bar -> .histogram__barswrapper-bar

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram_barswrapper {
.histogram_barswrapper -> .histogram__barswrapper

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-bottom: 16px;
а как же padding-right?)

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    border-radius: 50%;
margin-right: 16px

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 515px;
95%

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 257px;
60%

2021-12-16 09:19 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 172px;
40%

2021-12-16 13:00 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +    border-radius: 50%;
Сделано

2021-12-17 19:11 UTC, OursonSucre commented on 04-lection2/01-histogram/histogram.css
> +    flex-wrap: wrap;
Сделано!

2021-12-17 19:11 UTC, OursonSucre commented on 04-lection2/01-histogram/histogram.css
> +    padding-left: 24px;
Сделано!

2021-12-17 19:11 UTC, OursonSucre commented on 04-lection2/01-histogram/histogram.css
> +    padding-right: 29px;
Сделано!

2021-12-17 19:11 UTC, OursonSucre commented on 04-lection2/01-histogram/histogram.css
> +    padding-left: 24px;
Сделано!

2021-12-17 19:11 UTC, OursonSucre commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 26px;
Сделано!

2021-12-18 13:51 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-18 19:22 UTC, GSemikozov requested changes

2021-12-18 19:22 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    border-radius: 50%;
неа

2021-12-18 19:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-18 21:53 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +    border-radius: 50%;
Ага... Помечено как резолвд, ну я на всякий случай врапперу паддинг добавил)

2021-12-19 20:56 UTC, OursonSucre commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-bottom: 16px;
Добавлено!

2021-12-19 20:58 UTC, OursonSucre commented on 04-lection2/01-histogram/histogram.css
> +.histogram_barswrapper {
Точно. Это же элемент.

2021-12-19 20:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-19 21:00 UTC, OursonSucre commented on 04-lection2/01-histogram/histogram.css
> +.histogram_barswrapper__bar {
А это просто имя элемента с дефисом.

2021-12-19 21:11 UTC, GSemikozov approved these changes

2021-12-19 21:11 UTC, merged