add solution for 05-lection3_03-calendar
js-tasks-ru/htmlcss-20211125_voffkarus pull request #6
Opened 2021-12-20 15:53 UTC by OursonSucre

2021-12-20 15:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-20 20:13 UTC, GSemikozov requested changes

2021-12-20 20:13 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +padding-bottom: 12px;
все-таки margin

2021-12-20 20:13 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +grid-template-rows: repeat(6, 1fr);
если месяц начинается. например с. ппятницы, то тогда потребуется 7 рядов ..

2021-12-20 20:13 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +padding: 9px;
на всякий случай уточню - а паддинги тут обязательно указывать явно?

2021-12-20 20:13 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 9px;
и тут

2021-12-20 20:26 UTC, OursonSucre commented on 05-lection3/03-calendar/calendar.css
> +grid-template-rows: repeat(6, 1fr);
С субботы, в данном случае)) добавил и сдвинул начало на субботу)

2021-12-20 20:26 UTC, OursonSucre commented on 05-lection3/03-calendar/calendar.css
> +padding-bottom: 12px;
Поправил.

2021-12-21 19:52 UTC, OursonSucre commented on 05-lection3/03-calendar/calendar.css
> +padding: 9px;
Короче говоря без паддингов не удалось.

2021-12-21 19:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-22 10:46 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-22 11:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-22 15:45 UTC, GSemikozov approved these changes

2021-12-22 15:45 UTC, merged